# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bdh0404/clSPARSE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bdh0404/clSPARSE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bdh0404/clSPARSE/CMakeFiles /home/bdh0404/clSPARSE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bdh0404/clSPARSE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Boost

# Build rule for target.
Boost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Boost
.PHONY : Boost

# fast build rule for target.
Boost/fast:
	$(MAKE) -f CMakeFiles/Boost.dir/build.make CMakeFiles/Boost.dir/build
.PHONY : Boost/fast

#=============================================================================
# Target rules for targets named gMock

# Build rule for target.
gMock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gMock
.PHONY : gMock

# fast build rule for target.
gMock/fast:
	$(MAKE) -f CMakeFiles/gMock.dir/build.make CMakeFiles/gMock.dir/build
.PHONY : gMock/fast

#=============================================================================
# Target rules for targets named clSPARSE-samples

# Build rule for target.
clSPARSE-samples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clSPARSE-samples
.PHONY : clSPARSE-samples

# fast build rule for target.
clSPARSE-samples/fast:
	$(MAKE) -f CMakeFiles/clSPARSE-samples.dir/build.make CMakeFiles/clSPARSE-samples.dir/build
.PHONY : clSPARSE-samples/fast

#=============================================================================
# Target rules for targets named clSPARSE

# Build rule for target.
clSPARSE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clSPARSE
.PHONY : clSPARSE

# fast build rule for target.
clSPARSE/fast:
	$(MAKE) -f CMakeFiles/clSPARSE.dir/build.make CMakeFiles/clSPARSE.dir/build
.PHONY : clSPARSE/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Boost"
	@echo "... gMock"
	@echo "... clSPARSE-samples"
	@echo "... clSPARSE"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

